name: custom_adaptive_scaffold
description: Widgets to easily build adaptive layouts, including navigation elements.
version: 1.0.0
issue_tracker: https://github.com/hanskokx/custom_adaptive_scaffold/issues
repository: https://github.com/hanskokx/custom_adaptive_scaffold

environment:
  sdk: ^3.5.3
  flutter: ">=3.24.3"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  arcane_analysis: ^1.0.3
  flutter_test:
    sdk: flutter

topics:
  - layout
  - adaptive
  - responsive
